src/datasets/datasets.module.ts
src/datasets/schemas/dataset.schema.ts
src/main.ts

The code to set the mongodb document _id to the same value as the field pid.
This is needed when working in a mixed configuration where different endpoints are served by the two different backend implementation
* No new files added
* src/datasets/datasets.module.ts:  configured so Mongoose does not assign default value and value of pid field is assigned when new or empty 
* src/datasets/schemas/dataset.schema.ts : added _id field
* src/main.ts: added logging of mongodb url

Added setting _id in mongo as field pid on save new datasets

---

src/attachments/schemas/attachment.schema.ts
src/datablocks/schemas/datablock.schema.ts
src/datasets/schemas/dataset.schema.ts
src/initial-datasets/schemas/initial-dataset.schema.ts
src/instruments/schemas/instrument.schema.ts
src/jobs/jobs.module.ts
src/jobs/schemas/job.schema.ts
src/origdatablocks/schemas/origdatablock.schema.ts
src/policies/schemas/policy.schema.ts
src/proposals/schemas/proposal.schema.ts
src/published-data/schemas/published-data.schema.ts
src/samples/schemas/sample.schema.ts
src/users/schemas/role.schema.ts
src/users/schemas/user-identity.schema.ts
src/users/users.module.ts

Add the 
```
toJSON: {
getters: true
}
```
option to schemas where missing.
This makes mongoose change `_id` to `id` when returning documents from the database.
* Add getters to schemas where missing

Add getters to schemas where missing

---

src/attachments/schemas/attachment.schema.ts
src/datablocks/schemas/datablock.schema.ts
src/datasets/schemas/dataset.schema.ts
src/datasets/schemas/technique.schema.ts
src/initial-datasets/schemas/initial-dataset.schema.ts
src/instruments/schemas/instrument.schema.ts
src/jobs/schemas/job.schema.ts
src/origdatablocks/schemas/origdatablock.schema.ts
src/policies/schemas/policy.schema.ts
src/proposals/schemas/proposal.schema.ts
src/published-data/schemas/published-data.schema.ts
src/samples/schemas/sample.schema.ts

See #75 
For embedded document like Attachment, Technique, etc they can be empty/null if we don't add sparse the mongodb will index all documents even the ones that are `null` hence we get the exception. This PR add `sparse: true` which means only index the documents that contain the field to be indexed.
See #75
- Add sparse property to schema
- Remove unique: true property since `_id `is a special field and mongo db always index this field. Adding unique might cause problem since mongodb will think we want to create a custom index for `_id`.

removed unique prop and add sparse prop

---

src/proposals/schemas/proposal.schema.ts

See #77 
The type for `MeasurementPeriodList` was wrong
- Fix small mistake on type of `MeasurementPeriodList`
- Change type to Array

fix wrong type for MeasurementPeriodList

---

src/main.ts

Increase max payload size on POST requests from 100 kb to 16 mb to allow the creation of Attachments.
See issue #73.
* #73
* Set upper limit of POST request body to 16 mb

Increase max payload size to 16mb

---

src/datasets/schemas/technique.schema.ts

Fixes #121. There was a PR a few months ago that removed many unique index constraints, replacing them with sparse. This particular index was missed...it was made sparse but unique was not removed. This PR fixes that.
Tests pass.

Remove unique index on dataset.techniques

---

migrate-mongo-config.js
migrations/20220726224709-technique_index.js
package.json

This is experimental, would love some opinions before anyone thinks about merging.
Adds a package, migrate-mongo, to be able to manage database schema changes on the new backend.
Database migrations are a fairly standard practice, and there are a lot of tools out there to help manage the process of handling them during upgrades of the backend code. I hit the potential need in a recent PR, where I know that folks will want to drop and index after taking the changes.
I spent a little time playing with different tools. There are a couple of projects that use mongoose directly, but they are effectively dead. `migrate-mongo` appears to be well maintained and seemed to work for my very simple use case.
If this gets merged, we'll want to write some official documentation. Here's at least an …

Add migrate-mongo and a migration

---

Dockerfile
docker-compose.dev.yaml

Remove the explicit setting of the architecture to use and add the dist volume mount not to override the container dist folder with the one that might be present on the host
Setting the architecture had some drawbacks with different OS

Fix dockerfile to use default arch and mount dist

---

package-lock.json
package.json

Reverts SciCatProject/scicat-backend-next#200
nestjs/axios 1.0.0 breaks our code.

Revert "build(deps): bump @nestjs/axios from 0.1.0 to 1.0.0"

---

src/datasets/datasets.controller.ts
src/datasets/datasets.service.ts
src/datasets/dto/create-dataset.dto.ts
src/datasets/dto/update-dataset.dto.ts
src/datasets/dto/update-derived-dataset.dto.ts
src/datasets/dto/update-raw-dataset.dto.ts

This PR aims to refactor and improve the PUT endpoint on the datasets. PUT method should be idempotent(calling it once or several times successively has the same effect). Now PUT endpoint uses `findOneAndReplace` instead of acting exactly the same as PATCH where we used `findOneAndUpdate` doing partial update instead of replacement.
PUT method should be replacing instead of doing partial updates.
* https://jira.esss.lu.se/browse/SWAP-2942
* Changes are mainly in the dataset update/partial update DTOs, validation and controller logic.

Implement datasets PUT by standards

---

migrations/20220726224709-technique_index.js
migrations/20230125083116-migrate-id-field-to-pid.js
migrations/20230125143522-replace-object-ids.js

Adding all database migration scripts in one place.
Previously we had shell scripts and migrate-mongo scripts for initial database migration and needed two different ways of running them.
* https://jira.esss.lu.se/browse/SWAP-2982

feat: add all the migration scripts in one place to be able to run with migrate-mongo

---

src/datasets/datasets.controller.ts
src/logbooks/interceptors/users-logbooks.interceptor.ts
test/DatasetAuthorization.js
test/PublishedData.js

Fix permissions for following endpoints:
- GET /datasets/:id/thumbnail
- GET /datasets/:id/origdatablocks
- GET /datasets/:id/datablocks
- GET /datasets/:id/attachments
The above endpoints were not allowing unauthenticated user to access data on public datasets.
* https://jira.esss.lu.se/browse/SWAP-3084
* changes made

fix published dataset datablocks and attachments permissions

---

src/datasets/dto/create-dataset.dto.ts
test/DerivedDataset.js
test/RawDataset.js
test/TestData.js

Fix and test datasets with minimal required fields

fix: make ownerEmail optional and add minimal dataset testing

---

migrations/20230309125203-update-user-entries.js
migrations/20230309145701-update-user-indentity-entries.js

We added a dedicate field to collection User and UserIdentity to store which strategy the user was authenticated with 
This PR adds the migrate mongo scripts to update such collections to adhere to the new schema
The new backend implements a cleaner schema to store the user information and which strategy they used to authenticate with.
* added migration mongo scripts

added mongo migrate script to updated User and UserIdentity

---

src/casl/casl-ability.factory.ts
src/casl/guards/policies.guard.ts
src/users/users.controller.ts
src/users/users.service.ts
test/LoginUtils.js

This PR adds a user endpoint to check if the user specified is allowed to create datasets or not.
Users with admin privileges are allowed to check different users.
The frontend currently show the "Create Dataset" button in the dataset list page, no matter if the user logged in has the authorization to create the datasets or not.
We want the frontend to show/hide the button according to the user authorization. This endpoint should provide the info needed.
* user controller
* user service

Added user endpoint to return if user is authorized to create datasets

---

src/datasets/interceptors/fullquery.interceptor.ts
test/DatasetFilter.js
test/TestData.js

Operators like: GREATER_THAN, LESS_THAN, EQUAL_TO_NUMERIC and EQUAL_TO_STRING should work as expected in the conditional querying.
There was a bug inside the conditional querying using the above operators.
* https://jira.esss.lu.se/browse/SWAP-3154
* changes made

fix: fix fields conditional query should return correct results

---

src/origdatablocks/dto/create-origdatablock.dto.ts
src/origdatablocks/schemas/origdatablock.schema.ts
test/Instrument.js
test/RawDatasetOrigDatablock.js
test/TestData.js

when I create an origdatablock with field chkAlg field set to empty string, I receive a 500 error.
https://jira.esss.lu.se/browse/SWAP-3161

fix: create origdatablock with empty chkAlg causing 500 error

---

src/logbooks/interceptors/users-logbooks.interceptor.ts

Currently, admin can view logbooks in the proposal only when the proposal Id is included in the access group like other normal user.
As an admin I want to be able to access all logbooks in any proposals.
https://jira.esss.lu.se/browse/SWAP-3195

fix: admin should have access to all logbooks for proposals

---

src/users/dto/create-custom-jwt.dto.ts
src/users/users.controller.ts
src/users/users.service.ts

this PR adds the correct configuration for swagger for endpoint users/<id>/jwt
I realized that the swagger interface was not properly setup
* users files

Swap 3206 2 - updated swagger interface

---

src/config/configuration.ts
src/users/users.controller.ts
src/users/users.service.ts

Create custom JWT valid token
When we tested the tokens create through the JWT endpoint, we realized that they were not valid.
* user.service.ts
* user.controller.ts

SWAP 3206 3 - Refactor jwt endpoint to provide valid jwt

---

src/casl/action.enum.ts
src/casl/casl-ability.factory.ts
src/instruments/instruments.controller.ts
src/instruments/instruments.service.ts
src/instruments/schemas/instrument.schema.ts
test/Instrument.js
test/TestData.js

This PR fixes the filter issues on Instrument endpoint and extends the API tests.
Instrument endpoint was returning the incorrect instrument when filtering was applied or when the instrument id was being passed. Same for the patch one.
* filtering in main endpoint, path and findone
* casl ability factory
* instrument controller, service, and schema
* data for test
* instrument tests

Instrument endpoint and tests

---

src/instruments/dto/create-instrument.dto.ts
src/instruments/instruments.controller.ts
src/instruments/instruments.service.spec.ts
src/instruments/schemas/instrument.schema.ts
test/Instrument.js
test/InstrumentsFilter.js
test/TestData.js

This PR add the field unique name to the instrument, so an instrument can be uniquely identified by its id and unique name. The field name is allowed to be non unique
Following a discussion at the collaborator meeting, it has been noted that facilities can benefits from a unique instrument name and more user friendly name
* added uniqueName to instrument model
* updated tests
* instrument model, controller, service and tests

Swap 3226 2: add unique name to instrument

---

migrations/20230424064803-add-instrument-unique-name.js

This PR add the mongo migrate script to add the instrument unique name.
In this new backend, we added a unique name for instrument which did not exists in the old backend. We need to automatically create unique names.
* added mongo migrate script

added migration script to add uniqueName for instruments

---

migrations/20230309145701-update-user-indentity-entries.js

We had some Errors an this will fixed it. 
*  Error: Could not migrate up 20230309145701-update-user-indentity-entries.js: Class constructor ObjectId cannot be invoked without 'new'
* add new operator

add new operator to 20230309145701-update-user-indentity-entries.js

---

src/common/utils.ts
src/datasets/datasets.controller.ts
src/datasets/interfaces/dataset-filters.interface.ts
src/users/user-identities.controller.ts

This PR aims to make shared datasets available for users. Also prevents all users for being able to update datasets and leave that ability only for owners.
Anyone that has access to dataset could update or share it and people in sharedWith field were not able to access the datasets.
* https://jira.esss.lu.se/browse/SWAP-3274
* changes made

feat: enable dataset access for shared emails

---

src/datasets/datasets.md
src/datasets/dto/create-dataset.dto.ts
src/datasets/schemas/dataset.schema.ts

Fix typo in field descriptions

---

src/auth/auth.controller.ts
src/auth/auth.service.ts
src/users/users.controller.ts

Short description of the pull request
* Items added
* changes made

fix: Errors on logout

---

src/common/schemas/datafile.schema.ts

The properties for data file were not correctly set and all of them were marked as required.
This PR explicitly define if a field is required or not
During the development of Scitacean, we discovered that all the properties of DataFiles are required, which is not true.
* Define explicitly the required property in the DataFile schema

Fixed data properties for orig datablocks file

---

src/common/dto/datafile.dto.ts
src/origdatablocks/dto/create-origdatablock.dto.ts

This PR updates the model and dto for origdatablock and datafiles, so the swagger interface matches the requirements.
While working on Scitacean, we realized that the swagger interface was not matching the model requirements.
* datafile.dto.ts
* create-origdatablock.dto.ts

fixed orig datablock and datafile dto
