SciCatProject/scicat-backend-next

src/datablocks/schemas/datablock.schema.ts
src/origdatablocks/schemas/origdatablock.schema.ts
src/samples/schemas/sample.schema.ts

Fix for UUID generation
This PR aims to fix issue where new entries can not be created, by making sure new UUIDS are created when new items are created.
* src/datablocks/schemas/datablock.schema.ts (5e767bb)
* src/origdatablocks/schemas/origdatablock.schema.ts (5e767bb)
* src/samples/schemas/sample.schema.ts (5e767bb)

fix(uuid): fix new id uniqueness

---

src/datablocks/schemas/datablock.schema.ts
src/origdatablocks/schemas/origdatablock.schema.ts
src/samples/schemas/sample.schema.ts

fix: revert accidental merge

---

README.md
scripts/migrateIdFields.js
scripts/migrateIdFields.sh

Adds scripts for migrating id fields in MongoDB and a short guide on how to run them.
Make it easier for developers to get started on working with repo.
* Create *migrateIdFields.js* script in */scripts* folder
* Create *migrateIdFields.sh* script in */scripts* folder
* Add section on how to run migration scripts in *README.md*

Migration docs

---

src/common/utils.ts

See #76 
The function `appendSIUnitToPhysicalQuantity` migrated from current backend mutate the input object directly which means it only modifies physical quantities and leaves the other fields untouched. Since this function on the new backend doesnt mutate the input but create a branch new object we need to also handle the case where key has value which is empty, null, false etc...
See #76

fix disapeard fields

---

README.md

Add new step to get started section of README file, with link to explorer.
See issue #113 
* Fixes #113 
* Add new step to get started section.

Add new step to get started in README

---

README.md
test/Datablock.js
test/DatablockDerived.js
test/Dataset.js
test/DatasetLifecycle.js
test/DerivedDataset.js
test/Jobs.js
test/Policy.js
test/Proposal.js
test/RawDataset.js
test/ResetDataset.js
test/Sample.js

Short description of the pull request
* Items added
* changes made

test: adding and fixing e2e api tests from the old backend

---

.gitignore
status-tests/README.md
status-tests/extract-status-from-test-log.awk
status-tests/tests-status.md

This PR provides a current status on the test suite for the new backend. It also provides documentation on how to update it and the script to create the md table
WE nee to be able to easily monitor the status of the tests of the new backend as we move closer to the migration date
n/a
- added test-status folder with md and awk files

added test status

---

src/auth/auth.controller.ts
src/auth/auth.module.ts
src/auth/strategies/oidc.strategy.ts
src/config/configuration.ts

Small tweaks for oAuth with OIDC implementation
This PR addresses some TS improvements as well as improves readability
SWAP-2835

fix: improvements for oAuth implementation

---

Dockerfile
README.md
docker-compose.dev.yaml

This PR adds a docker-compose.dev.yaml file which spins up a dev environment 
Eases local deployment 
* docker-compose.dev.yaml added
* Dockerfile split in 3 parts, vs 2 before, to have one suited for local development

Add docker-compose file to ease local deployment

---

package-lock.json
package.json

Reverts SciCatProject/scicat-backend-next#186

Revert "build(deps): bump @nestjs/axios from 0.1.0 to 1.0.0"

---

.github/workflows/build-release.yaml

Simplify tagging, and make sure latest release is marked with stable

fix: tagging for release

---

src/datasets/datasets.controller.ts
src/datasets/datasets.service.ts
src/datasets/dto/create-dataset.dto.ts
src/datasets/dto/create-raw-dataset.dto.ts
src/datasets/dto/create-technique.dto.ts
src/datasets/interceptors/fullquery.interceptor.ts
src/datasets/schemas/dataset.schema.ts
src/datasets/schemas/history.schema.ts
src/datasets/schemas/lifecycle.schema.ts
src/datasets/schemas/relationship.schema.ts
src/datasets/schemas/technique.schema.ts
src/jobs/jobs.service.ts
src/proposals/proposals.controller.ts

Short description of the pull request
* Items added
* changes made

fix linting issues and add back the datasetlifecycle

---

src/auth/access-group-provider/access-group-from-graphql-api-call.service.ts
src/auth/access-group-provider/examples/ESS-example-access-group-service-factory.ts_example

This PR aims to fix the query that is sent to GQL server
Query needs to follow specific protocol

fix: query with axios

---

README.md

Update database migration documentation to use only migrate-mongo package instead of doing it manually using bash scripts.

Update migration documentation

---

Dockerfile
src/casl/casl-ability.factory.ts
src/datasets/datasets.controller.ts
src/proposals/interfaces/proposal-filters.interface.ts
src/proposals/proposals.controller.ts
test/DatasetAuthorization.js
test/Proposal.js
test/ProposalAuthorization.js
test/PublishedData.js
test/TestData.js

Proposals should be seen only by users with right permissions.
Proposals were seen by all users
* https://jira.esss.lu.se/browse/SWAP-3036
* https://jira.esss.lu.se/browse/SWAP-3081

Swap 3036 proposal access

---

package-lock.json
package.json
src/datasets/datasets.controller.ts
src/proposals/proposals.controller.ts
test/Proposal.js
test/RawDataset.js
test/TestData.js

Introduce faker and add more dataset tests using it to test with dynamic data that is not same all the time

fix: add more dynamic data for testing in the datasets

---

test/DatasetAuthorization.js
test/RandomizedDatasetPermissions.js

Add more tests with randomized big amount of data that are testing the dataset permissions.

test: Improve tests with big randomized amount of data

---

src/auth/auth.service.ts
src/policies/policies.service.ts
src/users/users.controller.ts

Token expiry date was wrong and not correctly set. The value read from the config was only returned to the frontend but not set inside the token itself.

fix: fix token expiry date

---

README.md
src/auth/auth.controller.ts
src/auth/auth.service.ts
src/auth/interfaces/jwt-user.interface.ts
src/auth/strategies/jwt.strategy.ts
src/config/configuration.ts
src/users/users.controller.ts
test/Auth.js

This PR adds the endpoint and solved the issues with the returned status and value
FE was performing a logout through endpoint users/logout which did not exists. 
* user controller: added logout endpoint
* auth controller: fixed logout endpoint
* auth service: manage logout tasks

Swap 3175 - fixed logout issues

---

src/auth/auth.controller.ts
src/config/configuration.ts

Make OIDC return URL configurale
* Items added
* changes made
- [ -] Included for each change/fix?
- [ -] Docs updated?
- [ -] New packages used/requires npm install? 
- [ -] Toggle added for new features?

Oidc: correct and configurable return url

---

src/auth/access-group-provider/access-group-from-graphql-api-call.service.ts
src/auth/access-group-provider/access-group-from-multiple-providers.service.ts
src/auth/access-group-provider/access-group-from-payload.service.ts
src/auth/access-group-provider/access-group-from-static-values.service.ts

This PR adds logging to the access group functionalities.
Once we deployed BE v4 in staging, the user groups where not correct and we realized that it was hard to troubleshoot the issue.
* src/auth/access-group-provider

added logging to access groups authentication functions

---

src/published-data/published-data.controller.ts
test/PublishedData.js

Short description of the pull request
* Items added
* changes made

fix: Should be able to fetch published data by id without authorization

---

src/published-data/published-data.controller.ts
src/published-data/published-data.service.ts

Fixing filters and limits on the published data endpoint.
Filters and limits were not working properly on published data.
* https://jira.esss.lu.se/browse/SWAP-3326
* changes made

feat: Make the published data work with filters and limits
